packages:
  - apps/**
  - packages/**
  - libs/**

onlyBuiltDependencies:
  - '@mui/x-telemetry'
  - '@nestjs/core'
  - '@scarf/scarf'
  - '@tailwindcss/oxide'
  - bcrypt
  - esbuild
  - protobufjs
  - unrs-resolver
